apiVersion: v1
data:
  keyfile: U0VDUkVULUtFWQo=
  message: SGVsbG8gV29ybGQh
kind: Secret
metadata:
  creationTimestamp: "2023-02-09T12:52:04Z"
  name: sample-secret
  namespace: default
  resourceVersion: "52346"
  uid: f01f03e5-4908-407b-9e6b-192d50b34712
type: Opaque

---
apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  containers:
  - name: sample
    image: nginx:1.17.2-alpine
    env:
    - name: MESSAGE
      valueFrom:
        secretKeyRef:
          name: sample-secret
          key: message
    volumeMounts:
    - name: secret-storage
      mountPath: /home/nginx
  volumes:
  - name: secret-storage
    secret:
      secretName: sample-secret
      items:
      - key: keyfile
        path: keyfile
